# This file is used to run the mailu/setup utility

version: '3.6'

services:
  redis:
    image: redis:alpine
    networks:
      - default
    restart: always

  development:
    image: ghcr.io/mailu/setup:${DEVELOPMENT}
    networks:
      - web
      - default
    env_file: .env
    environment:
      stable_version: ${STABLE}
      this_version: ${DEVELOPMENT}
      VERSIONS: ${STABLE},${DEVELOPMENT}
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${DEVELOPMENT}
    depends_on:
      - redis
    restart: always

  stable:
    image: ghcr.io/mailu/setup:${STABLE}
    networks:
      - web
      - default
    env_file: .env
    environment:
      stable_version: ${STABLE}
      this_version: ${STABLE}
      VERSIONS: ${STABLE},${DEVELOPMENT}
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.root.frontend.redirect.regex=.*
      - traefik.root.frontend.redirect.replacement=/${STABLE}/
      - traefik.root.frontend.rule=Host:${ADDRESS};PathPrefix:/
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${STABLE}
    depends_on:
      - redis
    restart: always

networks:
  web:
    external: true
  default:
    external: false
