version: "3.8"

networks:
  default:
  coolify:
    external: true

services:
  front:
    image: ${MAILU_VERSION:-mailu/nginx:latest}
    env_file: .env
    restart: always
    networks:
      - default
      - coolify
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailu.rule=Host(`mail.morrisdesigns.art`)
      - traefik.http.routers.mailu.entrypoints=https
      - traefik.http.services.mailu.loadbalancer.server.port=80

  admin:
    image: ${MAILU_VERSION:-mailu/admin:latest}
    env_file: .env
    restart: always
    networks:
      - default

  imap:
    image: ${MAILU_VERSION:-mailu/dovecot:latest}
    env_file: .env
    restart: always
    networks:
      - default

  smtp:
    image: ${MAILU_VERSION:-mailu/postfix:latest}
    env_file: .env
    restart: always
    networks:
      - default

  antispam:
    image: ${MAILU_VERSION:-mailu/rspamd:latest}
    env_file: .env
    restart: always
    networks:
      - default

  antivirus:
    image: ${MAILU_VERSION:-mailu/clamav:latest}
    env_file: .env
    restart: always
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    networks:
      - default
